# .github/workflows/deploy.yml

name: Deploy WordPress Theme

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" > .env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
        working-directory: ./

      - name: Install Composer dependencies
        run: composer install
        working-directory: ./

      - name: Deploy to Hostinger (Production)
        if: ${{ github.event.inputs.environment == 'production' || github.event_name == 'push' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: domains/lesjeunesailesdegatineau.ca/public_html/wp-content/themes/lesjeunesailesdegatineau/
          dangerous-clean-slate: false

      - name: Deploy to Raspberry Pi (Development)
        if: ${{ github.event.inputs.environment == 'development' }}
        uses: appleboy/sftp-action@v0.0.9
        with:
          host: ${{ secrets.SFTP_SERVER_DEV }}
          username: ${{ secrets.SFTP_USERNAME_DEV }}
          password: ${{ secrets.SFTP_PASSWORD_DEV }}
          port: 22
          source: "./*"
          target: "/var/www/html/wp-content/themes/lesjeunesailesdegatineau/"
